version: '3.7'

services:
  device_db:
    image: postgres:latest
    container_name: device_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - device_db_data:/var/lib/postgresql/data/

volumes:
  device_db_data: